# Generated by Django 3.1 on 2020-10-12 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResembleTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_ejecución', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=False)),
                ('imagen1', models.ImageField(upload_to='')),
                ('observacionesImagen1', models.CharField(max_length=256)),
                ('imagen2', models.ImageField(upload_to='')),
                ('observacionesImagen2', models.CharField(max_length=256)),
                ('imagen3', models.ImageField(upload_to='')),
                ('observacionesImagen3', models.CharField(max_length=256)),
            ],
        ),
    ]
